# Fly.io app configuration

app = "riverstone-voice-svc"
primary_region = "syd"

[build]
# Uses the Dockerfile in repo

[env]
# Ensure the app binds to Fly's internal port
BIND = "0.0.0.0:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

[[mounts]]
  source = "data"
  destination = "/data"
